- name: install nginx and run 
  host: frontend
  tasks:
   - name: install nginx server 
     ansible.builtin.package:
      name: nginx
      state: present
   - name: run nginx
     ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes  